FROM python:3.13.7

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN python -m pip install -r /code/requirements.txt

COPY . /code/

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]